#!/bin/sh
set -e

ln -sf /usr/lib/encryptsync/encryptsyncctl.py /usr/bin/encryptsyncctl
chmod +x /usr/lib/encryptsync/encryptsyncctl.py

case "$1" in
  configure)
    # scripts perms
    install -m 0755 -d /usr/lib/encryptsync/scripts/pam
    chmod 0755 /usr/lib/encryptsync/scripts/pam/pam-session-open.sh || true
    chmod 0755 /usr/lib/encryptsync/scripts/pam/pam-session-close.sh || true

    # activate pam snippet
    if command -v pam-auth-update >/dev/null 2>&1; then
      pam-auth-update --package --enable encryptsync || true
    fi
    ;;
esac

#DEBHELPER#

exit 0